src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $Telephone = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'users', targetEntity:Facture::class)]
    private Collection $factures;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }


    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function __toString()
    {
        return $this->Nom;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->Telephone;
    }

    public function setTelephone(string $Telephone): self
    {
        $this->Telephone = $Telephone;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Facture>
     */
    public function getFactures(): Collection
    {
        return $this->factures;
    }

    public function addFacture(Facture $facture): self
    {
        if (!$this->factures->contains($facture)) {
            $this->factures->add($facture);
            $facture->setUsers($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): self
    {
        if ($this->factures->removeElement($facture)) {
            // set the owning side to null (unless already changed)
            if ($facture->getUsers() === $this) {
                $facture->setUsers(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            // ->add('plainPassword', TextType::class, [
            //     "mapped" => false
            // ])
            ->add('Adresse')
            ->add('Nom')
            ->add('Prenom')
            ->add('Telephone')
            // ->add('isVerified')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;


use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/profile')]
class UserController extends AbstractController
{

    #[Route('/', name: 'app_user_show', methods: ['GET'])]
    public function show(): Response
    {
        $user= $this->getUser();
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, UserRepository $userRepository): Response
    {
        $user= $this->getUser();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_show', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }
}

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1 <div class=" row m-4 text-center"> Modifier mon Profile</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Enregistrer'}) }}

    <a href="{{ path('app_user_show') }}">Annuler</a>

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}utilisateur{% endblock %}

{% block body %}

<head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="{{ asset('css/btn.css') }}">
    <link rel="stylesheet" href="{{ asset('css/user.css') }}">
    <script src="{{ asset('js/home.js') }}" defer></script>
</head>
{# <h1>Mon compte</h1>

<table class="table">
    <tbody>
        <tr>
            <th>Email</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Password</th>
            <td>{{ user.password }}</td>
        </tr>
        <tr>
            <th>Adresse</th>
            <td>{{ user.Adresse }}</td>
        </tr>
        <tr>
            <th>Nom</th>
            <td>{{ user.Nom }}</td>
        </tr>
        <tr>
            <th>Prenom</th>
            <td>{{ user.Prenom }}</td>
        </tr>
        <tr>
            <th>Telephone</th>
            <td>{{ user.Telephone }}</td>
        </tr>
        <tr>
            <th>Compte vérifié</th>
            <td>{{ user.isVerified ? 'Yes' : 'No' }}</td>
        </tr>
    </tbody>
</table>

<br>
<a href="{{ path('app_user_edit', {'id': user.id}) }}">Modifier</a> #}

<h1 class="text-center">
    Mon compte
</h1>
<table class="table">
    <div class=" row m-4 text-center">
        <div class="card border-dark mt-6 m-4">
            <div class="col-xl-12 col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <img class="d-block mx-auto p-2 mb-1 mt-4 " style="width:200px; height:auto" src="/img/test/toucan.jpg"
                    alt=" oiseauchoucador">
            </div>
            <div class="col-xl-12 col-lg-4 col-md-6 col-sm-12 col-xs-12"">
                <div class="card-body  ">
                    <p class="card-title">
                        {{ user.nom }}
                    </p>
                    <p class="card-text">
                        {{ user.prenom }}
                    </p>
                    <p class="card-text">
                        {{ user.email }}
                    </p>
                    <p class="card-text">
                        {{ user.telephone }}
                    </p>
                    <p class="card-text">
                        {{ user.adresse }}
                    </p>
                    <p class="card-text">
                        Compte vérifié : {{ user.isVerified ? 'Yes' : 'No' }}
                    </p>
                    <a href="{{ path('app_user_edit', {'id': user.id}) }}">
                        <button type="button" class="btn btn-primary">
                            Modifier mon profile
                        </button>
                    </a>
                </div>
                <a style="color: black;" href="{{ path('app_forgot_password_request') }}"> Mot de passe oublié </a>
            </div>
        </div>
    </div>
</table>
{% endblock %}